# Nombre del flujo de trabajo que verás en la pestaña "Actions" de GitHub
name: Build and Deploy to GitHub Pages

# Define cuándo se debe ejecutar este flujo: cada vez que haces un 'push' a la rama 'main'
on:
  push:
    branches: [ "main" ]

# Permisos necesarios para que la acción pueda escribir en la rama 'gh-pages'
permissions:
  contents: write

# Define las tareas que se van a ejecutar
jobs:
  build-and-deploy:
    # Usa la última versión de Ubuntu como sistema operativo virtual
    runs-on: ubuntu-latest
    steps:
      # 1. Clona tu repositorio en el entorno virtual
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      # 2. Reemplaza los placeholders en el archivo de configuración con los secretos
      - name: Replace Firebase config placeholders 🤫
        run: |
          sed -i 's|%FIREBASE_API_KEY%|${{ secrets.FIREBASE_API_KEY }}|g' firebase-config.js
          sed -i 's|%FIREBASE_AUTH_DOMAIN%|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g' firebase-config.js
          sed -i 's|%FIREBASE_PROJECT_ID%|${{ secrets.FIREBASE_PROJECT_ID }}|g' firebase-config.js
          sed -i 's|%FIREBASE_STORAGE_BUCKET%|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g' firebase-config.js
          sed -i 's|%FIREBASE_MESSAGING_SENDER_ID%|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g' firebase-config.js
          sed -i 's|%FIREBASE_APP_ID%|${{ secrets.FIREBASE_APP_ID }}|g' firebase-config.js
          sed -i 's|%FIREBASE_MEASUREMENT_ID%|${{ secrets.FIREBASE_MEASUREMENT_ID }}|g' firebase-config.js

      # 3. Despliega los archivos modificados a la rama 'gh-pages'
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          # La opción de abajo limpia el historial de la rama gh-pages para mantenerla limpia
          force_orphan: true